fix: 7.0 support
NativeScript/nativescript-unit-test-runner pull request #43
Opened 2020-07-30 10:11 UTC by farfromrefug

Move to esm to support 7.0
All pieces need to be updated!

2020-09-24 21:42 UTC, PeterStaev requested changes

2020-09-24 21:42 UTC, PeterStaev commented on tsconfig.json
> +        "module": "esnext",
Compile options are wrong and creates problems. See https://github.com/NativeScript/nativescript-cli/issues/5396

2020-09-24 21:44 UTC, farfromrefug commented on tsconfig.json
> +        "module": "esnext",
They need to be this. Just the hooks need to be build differently.
here is an example https://github.com/nativescript-community/l/blob/master/package.json#L47

2020-09-30 15:24 UTC, NathanWalker commented on tsconfig.json
> +        "module": "esnext",
@farfromrefug is this in operational form in it's current state or are there other stack related items that must be updated that you see? Curious if you've manually packed these changes and seen unit testing restored?

2020-09-30 15:42 UTC, farfromrefug commented on tsconfig.json
> +        "module": "esnext",
@NathanaelA no it needs to be done. The hook wont work if not es2015. And the unit test project itself needs to be build in es2017

2020-10-10 18:23 UTC, NathanWalker commented
Thanks @farfromrefug - @edusperoni was able to assist with the final piece and got unit testing support restored with 1.0.2 from this pr: https://github.com/NativeScript/nativescript-unit-test-runner/pull/44 👍

2020-10-10 18:23 UTC, closed without merging